project:
  title: "green-anole-litter"
  type: website
  output-dir: docs

website:
  navbar:
    left:
    - href: home.qmd
      text: Start Here
    - href: time-for-space.qmd
      text: Time-for-Space
    - href: lizard-overfilling.qmd
      text: Lizard Overfilling
    - href: biophysical-modeling.qmd
      text: Biophysical Modeling
    - href: memos.qmd
      text: Mechanistic Envelope Models

format:
  html:
    theme: cosmo
    toc: true
    lightbox: true

knitr:
  opts_chunk:
    dev: png
    dpi: 350