project:
  title: "green-anole-litter"
  type: website
  output-dir: docs

website:
  navbar:
    left:
    - href: home.qmd
      text: Start Here
    - href: live-beyond-ctmin.qmd
      text: Living Below CT<sub>min</sub>
    - href: leaf-litter-retreat.qmd
      text: Leaf Litter Retreat
    - href: biophysical-modeling.qmd
      text: Biophysical Modeling
    - href: memos.qmd
      text: Mechanistic Envelope Models

format:
  html:
    theme: cosmo
    toc: true
    lightbox: true

knitr:
  opts_chunk:
    dev: png
    dpi: 350