project:
  title: "green-anole-litter"
  type: website
  output-dir: docs

website:
  navbar:
    left:
    - href: home.qmd
      text: Start Here
    - href: space-by-time.qmd
      text: Space-by-Time

format:
  html:
    theme: cosmo

knitr:
  opts_chunk:
    dev: png
    dpi: 350