---
title: "Green anoles retreat to the leaf litter to avoid extreme cold"
format:
  html:
    code-fold: true
    fig-dpi: 300
---

```{r r-setup, warning = FALSE, message = FALSE}
# packages
library(tidyverse)
library(kableExtra)
library(ggpubr)
library(broom)
library(suncalc)

# options
options(
  dplyr.summarise.inform = FALSE,
  knitr.table.html.attr = "quarto-disable-processing=true"
)

```

## Overview

## Green anoles retreat to the leaf litter

```{r plot-survey-data}
#| fig-align: center
#| fig-width: 8
#| fig-height: 7
#| out.width: 66%

otms_data <- readRDS("data/otms-data.rds")

# latitudes of locations
otms_data <- otms_data |>
  mutate(
    lat = case_when(
      location == "MIA" ~ 25.7617,
      location == "PSL" ~ 27.305,
      location == "ORL" ~ 28.5383,
      location == "GNV" ~ 29.6516,
      location == "ATL" ~ 33.7490
    )
  )

# predict CTmin by latitude
pred_ctmin <- tibble(
  lat = seq(25, 35, by = 0.1),
  ctmin = 57 - 1.68 * lat - 41.67 + 1.48 * lat
)

# read and summarize survey data
survey <- readRDS("data/sleepy-lizard-survey-data.rds")
survey_sum <- survey |>
  group_by(year, doy) |>
  summarise(
    count = n() - 1,
    presence = ifelse(count > 0, 1, 0)
  ) |>
  mutate(
    continuous_doy = ifelse(year == 2026, doy + 365, doy)
  ) |>
  filter(continuous_doy < (365 + 30)) |>
  mutate(
    date = as.Date(paste(year, doy), format = "%Y %j")
  ) |>
  ungroup()

# estimate sunset times for Atlanta, GA
my_year <- 2026
my_dates <- seq(
  as.Date(sprintf("%d-01-01", my_year)),
  as.Date(sprintf("%d-12-31", my_year)),
  by = "day"
)
my_lat <- 33.7490
my_lon <- -84.3880
sunset_times <- getSunlightTimes(
  date = my_dates,
  lat = my_lat,
  lon = my_lon,
  keep = "sunset",
  tz = "America/New_York"
)
sunset_times$doy <- yday(sunset_times$date)
sunset_times$mod_sunset <- hour(sunset_times$sunset) * 60 + minute(sunset_times$sunset) # nolint
sunset_times <- sunset_times |> select(doy, mod_sunset)

# filter otm data
otm_data_ATL <- otms_data |>
  filter(location == "ATL") |>
  arrange(id, year, doy, mod) |>
  filter(microhabitat %in% c("branch", "leaflitter")) |>
  left_join(sunset_times, by = "doy") |>
  filter(mod > mod_sunset & mod < mod_sunset + 60) |>
  mutate(
    year = year + 2000
  ) |>
  mutate(
    temp = ifelse(year == 2025 & doy < 200, NA, temp),
    temp = ifelse(year == 2026 & doy > 30, NA, temp),
  ) |>
  filter(!is.na(temp)) |>
  group_by(year, doy, microhabitat) |>
  summarise(
    mean_temp = mean(temp, na.rm = TRUE),
    max_temp = max(temp, na.rm = TRUE),
    min_temp = min(temp, na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(
    date = as.Date(paste(year, doy), format = "%Y %j")
  )

# predict CTmin at ATL latitude
ctmin_atl <- 57 - 1.68 * my_lat - 41.67 + 1.48 * my_lat

# plot observation probability and OTM data
obs_plot <- ggplot() +
  geom_hline(
    yintercept = c(1, 0, 6.8 / max(otm_data_ATL$mean_temp, na.rm = TRUE)),
    linetype = "dashed",
    color = c("gray80", "darkblue", "steelblue"),
    alpha = 0.5
  ) +
  annotate(
    "label",
    x = as.Date("2025-10-01"),
    y = ctmin_atl / max(otm_data_ATL$mean_temp, na.rm = TRUE) + 0.05,
    label = expression(CT[min]),
    color = "steelblue",
    size = 5,
    fill = "white",
    vjust = 1
  ) +
  geom_line(
    data = filter(otm_data_ATL, microhabitat == "branch"),
    aes(x = date, y = mean_temp / max(otm_data_ATL$mean_temp, na.rm = TRUE)),
    color = "forestgreen", linewidth = 1
  ) +
  geom_line(
    data = filter(otm_data_ATL, microhabitat == "leaflitter"),
    aes(x = date, y = mean_temp / max(otm_data_ATL$mean_temp, na.rm = TRUE)),
    color = "darkorange", linewidth = 1
  ) +
  geom_point(
    data = survey_sum,
    aes(x = date, y = presence),
    color = "darkgray", size = 3, alpha = 0.75
  ) +
  geom_smooth(
    data = survey_sum,
    aes(x = date, y = presence),
    method = "glm",
    formula = y ~ x,
    method.args = list(family = binomial(link = "logit")),
    color = "black", se = FALSE, linewidth = 1.25
  ) +
  scale_y_continuous(
    name = "Observation Probability",
    sec.axis = sec_axis(
      ~ . * max(otm_data_ATL$mean_temp, na.rm = TRUE),
      name = "Lizard Body Temperature (°C)"
    ),
    breaks = seq(0, 1, 0.2)
  ) +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%b-%Y"
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(
      color = "black", fill = NA, linewidth = 0.5
    ),
    axis.ticks = element_line(color = "black", linewidth = 0.25),
    panel.grid = element_blank(),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 12),
    axis.text.x = element_text(size = 11)
  ) +
  labs(color = NULL)

# plot survey counts and OTM data
count_plot <- ggplot() +
  geom_hline(
    yintercept = c(0, ctmin_atl),
    linetype = "dashed",
    color = c("darkblue", "steelblue"),
    alpha = 0.5
  ) +
  annotate(
    "label",
    x = as.Date("2025-10-01"),
    y = ctmin_atl  + 0.05,
    label = expression(CT[min]),
    color = "steelblue",
    size = 5,
    fill = "white",
  ) +
  geom_line(
    data = filter(otm_data_ATL, microhabitat == "branch"),
    aes(x = date, y = mean_temp, color = "Canopy"),
    linewidth = 1
  ) +
  geom_line(
    data = filter(otm_data_ATL, microhabitat == "leaflitter"),
    aes(x = date, y = mean_temp, color = "Leaf litter"),
    linewidth = 1
  ) +
  geom_point(
    data = survey_sum,
    aes(x = date, y = count),
    color = "darkgray", size = 3, alpha = 0.75
  ) +
  geom_smooth(
    data = survey_sum,
    aes(x = date, y = count),
    method = "glm",
    formula = y ~ x,
    method.args = list(family = poisson(link = "log")),
    color = "black", se = FALSE, linewidth = 1.25
  ) +
  scale_y_continuous(
    name = "Green Anole Count",
    sec.axis = sec_axis(
      ~ .,
      name = "Lizard Body Temperature (°C)"
    )
  ) +
  scale_x_date(
    date_breaks = "1 month",
    date_labels = "%b-%Y"
  ) +
  scale_color_manual(
    values = c("Canopy" = "forestgreen", "Leaf litter" = "darkorange")
  ) +
  theme_minimal() +
  theme(
    panel.border = element_rect(
      color = "black", fill = NA, linewidth = 0.5
    ),
    axis.ticks = element_line(color = "black", linewidth = 0.25),
    panel.grid = element_blank(),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 12),
    axis.text.x = element_text(size = 11),
    legend.position = c(0.98, 0.98),
    legend.justification = c(1, 1),
    legend.text = element_text(size = 14),
    legend.key.spacing.y = unit(0.5, "lines")
  ) +
  labs(color = NULL)

ggarrange(
  obs_plot,
  count_plot,
  ncol = 1,
  nrow = 2,
  labels = c("A", "B"),
  align = "hv",
  # increase the size of the labels
  font.label = list(size = 16, face = "bold")
)

```

```{r model-retreating-temp}
survey_sum_model <- survey_sum |>
  left_join(
    filter(otm_data_ATL, microhabitat == "branch"),
    by = c("year", "doy", "date")
  )

# model
mod <- glm(
  presence ~ mean_temp,
  data = survey_sum_model,
  family = binomial(link = "logit")
)
broom::tidy(mod)
broom::glance(mod)

# get temperature thresholds for probabilities
probabilities <- c(0.01, 0.05, 0.1, 0.2, 0.25, 0.5)
thresholds <- tibble(
  probability = probabilities,
  temperature = (log(probabilities / (1 - probabilities)) - coef(mod)[1]) / coef(mod)[2] # nolint
) |>
  mutate(
    temperature = round(temperature, 2)
  )
thresholds |>
  kbl(
    col.names = c(
      "Observation Probability",
      "Predicted Lizard Body Temperature (°C)"
    ),
    align = "c"
  ) |>
  kable_styling(
    full_width = FALSE,
    position = "center"
  )
```

```{r plot-threshold-temperature}
#| fig-align: center
#| fig-width: 5
#| fig-height: 5
#| out.width: 66%

tret <- survey_sum |>
  left_join(
    filter(otm_data_ATL, microhabitat == "branch"),
    by = c("year", "doy", "date")
  ) |>
  ggplot(aes(x = mean_temp, y = presence)) +
  geom_vline(
    xintercept = c(0, 6.8, 8.8),
    linetype = "dashed",
    color = c("darkblue", "steelblue", "lightblue")
  ) +
  geom_jitter(
    color = "gray", size = 4, alpha = 0.75,
    width = 0, height = 0.02
  ) +
  annotate(
    "label",
    x = c(0, 6.8, 8.8),
    y = c(0.5, 0.75, 0.9),
    label = c(
      expression(bold(0 * degree * C)),
      expression(bold(CT[min])),
      expression(bold(T[ret]))
    ),
    color = c("darkblue", "steelblue", "lightblue"),
    fill = "white",
    alpha = 1,
    linewidth = 0,
    hjust = c(-0.01, 0.5, 0.5),
    size = 5
  ) +
  geom_smooth(
    method = "glm",
    formula = y ~ x,
    method.args = list(family = binomial(link = "logit")),
    color = "black", fill = "gray80",
    se = TRUE, linewidth = 1, alpha = 0.5,
    fullrange = TRUE
  ) +
  theme_minimal() +
  theme(
    axis.ticks = element_line(color = "black", linewidth = 0.25),
    axis.line = element_line(color = "black", linewidth = 0.5),
    panel.grid = element_blank(),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10)
  ) +
  labs(
    x = "Lizard Body Temperature in Canopy (°C)",
    y = "Observation Probability"
  )
tret
```

## The leaf litter buffers environmental temperatures

```{r plot-leaf-litter-buffering}
#| fig-align: center
#| fig-width: 5
#| fig-height: 5
#| out.width: 66%

# summarise data
otms_data_sum <- otms_data |>
  mutate(
    year = year + 2000,
    date = as.Date(paste(year, doy), format = "%Y %j"),
    month = format(date, "%b")
  ) |>
  filter(month %in% c("Jan")) |>
  group_by(location, lat, id, year, microhabitat, doy) |>
  summarise(
    min_temp = min(temp, na.rm = TRUE)
  ) |>
  ungroup()

# plot
buffering_plot <- otms_data_sum |>
  mutate(
    location = factor(location, levels = c("ATL", "GNV", "ORL", "PSL", "MIA"))
  ) |>
  ggplot(aes(x = lat, y = min_temp)) +
  geom_hline(
    yintercept = c(0),
    linetype = "dashed",
    color = "darkblue"
  ) +
  geom_hline(
    linetype = "dashed",
    aes(yintercept = 6.8, color = "CTmin"),
    show.legend = TRUE
  ) +
  geom_hline(
    linetype = "dashed",
    aes(yintercept = 8.8, color = "Tret"),
    show.legend = TRUE
  ) +
  geom_smooth(
    aes(color = microhabitat),
    method = "lm",
    se = FALSE,
  ) +
  stat_summary(
    aes(color = microhabitat),
    position = position_dodge(width = 0.75),
    fun.data = mean_sdl,
    fun.args = list(mult = 1),
    size = 1
  ) +
  geom_text(
    data = otms_data_sum |>
      group_by(location) |>
      summarise(
        lat = mean(lat),
        min_temp_mean = mean(min_temp[microhabitat == "leaflitter"]),
        min_temp_sd = sd(min_temp[microhabitat == "leaflitter"]),
        .groups = "drop"
      ),
    aes(x = lat, y = min_temp_mean + min_temp_sd + 0.5, label = location),
    inherit.aes = FALSE,
    vjust = -0.75,
    color = "darkgray",
    fontface = "bold"
  ) +
  scale_color_manual(
    values = c(
      "branch" = "forestgreen",
      "leaflitter" = "darkorange",
      "CTmin" = "steelblue",
      "Tret" = "skyblue"
    ),
    name = "Microhabitat",
    breaks = c("branch", "leaflitter", "CTmin", "Tret"),
    labels = c(
      "Canopy", "Leaf litter", expression(CT[min]), expression(T[ret])
    )
  ) +
  scale_x_continuous(
    breaks = seq(25, 35, by = 2.5),
    limits = c(25, 35),
    expand = c(0, 0)
  ) +
  theme_minimal() +
  theme(
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    panel.grid = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.98, 0.98),
    legend.justification = c("right", "top"),
    legend.text = element_text(size = 14),
    legend.key.spacing.y = unit(0.5, "lines")
  ) +
  labs(
    x = "Latitude (°N)",
    y = "Minimum Lizard Body Temperature (°C)"
  )
buffering_plot

```

```{r stats-leaf-litter-buffering}
# model
mod <- lm(min_temp ~ lat * microhabitat, data = otms_data_sum)
broom::tidy(mod)
broom::glance(mod)
```

```{r table-leaf-litter-buffering}
otms_data_sum |>
  group_by(location, lat, microhabitat, id) |>
  summarise(
    mean_min_temp = mean(min_temp, na.rm = TRUE),
    abs_min_temp = min(min_temp, na.rm = TRUE)
  ) |>
  group_by(location, lat, microhabitat) |>
  summarise(
    mean_mt = mean(mean_min_temp, na.rm = TRUE),
    sd_mt = sd(mean_min_temp, na.rm = TRUE),
    abs_mt = mean(abs_min_temp, na.rm = TRUE)
  ) |>
  mutate(
    est = paste(
      round(mean_mt, 1), "±",
      round(sd_mt, 1), "°C (min =", round(abs_mt, 1), ")"
    ),
  ) |>
  mutate(
    microhabitat = ifelse(microhabitat == "branch", "Canopy", "Leaf litter")
  ) |>
  select(location, lat, microhabitat, est, mean_mt) |>
  pivot_wider(
    names_from = microhabitat,
    values_from = c(est, mean_mt)
  ) |>
  mutate(
    buffering = round(`mean_mt_Leaf litter` - mean_mt_Canopy, 1)
  ) |>
  select(location, lat, est_Canopy, `est_Leaf litter`, buffering) |>
  kbl(
    col.names = c(
      "Location", "Latitude (°N)", "Canopy",
      "Leaf litter", "Average Buffering (°C)"
    ),
    align = "c",
  ) |>
  kable_styling(
    full_width = FALSE,
    position = "center",
    font_size = 12
  )
```

## Manuscript Figure

```{r plot-manuscript-figure}
#| fig-align: center
#| fig-width: 9
#| fig-height: 4.5
#| out.width: 100%

ggarrange(
  tret,
  buffering_plot,
  ncol = 2,
  nrow = 1,
  widths = c(1, 1),
  labels = c("A", "B"),
  font.label = list(size = 16, face = "bold")
)

```