---
title: "Mechanistic Envelope Models"
format:
  html:
    code-fold: true
    fig-dpi: 300
---

```{r r-setup, warning = FALSE, message = FALSE}
# packages
library(tidyverse)
library(NicheMapR)
library(kableExtra)
library(viridis)

# options
options(
  dplyr.summarise.inform = FALSE,
  knitr.table.html.attr = "quarto-disable-processing=true"
)

```

```{r load-data}

microclimate_temps <- readRDS("data/microclimate_temps.rds")

# define temperature thresholds
lethal <- 0
ctmin <- 5.35
retreat <- 6.6

# define thresholds
thresholds <- microclimate_temps |>
  filter(z == 1.8) |>
  mutate(
    thresh = case_when(
      min_annual_tb < lethal ~ "lethal",
      min_annual_tb >= lethal & min_annual_tb < ctmin ~ "ctmin",
      min_annual_tb >= ctmin & min_annual_tb < retreat ~ "retreat",
      TRUE ~ "rest"
    )
  ) |>
  select(lon, lat, thresh)

# merge microclimate temps with thresholds
microclimate_temps <- merge(
  microclimate_temps,
  thresholds,
  by = c("lon", "lat"),
  all.x = TRUE
)
```

```{r tss-calculation, eval = FALSE}
# define conditions to test
threshold_names <- unique(microclimate_temps$thresh)
veg <- seq(0, 1, by = 0.01)
heights <- unique(microclimate_temps$z)

# create grid to store values
tss_grid <- expand.grid(
  thresh = threshold_names,
  veg = veg,
  z = heights
)
tss_grid$tss <- NA_real_

# loop through thresholds, tree covers, and heights to calculate TSS
for (i in seq_len(nrow(tss_grid))) {

  # add progress tracker
  cat("Processing row", i, "of", nrow(tss_grid), "\n")

  if (tss_grid$thresh[i] == "lethal") {
    data_subset <- microclimate_temps |>
      filter(
        thresh == "lethal",
        z == tss_grid$z[i]
      )
  } else if (tss_grid$thresh[i] == "ctmin") {
    data_subset <- microclimate_temps |>
      filter(
        thresh %in% c("lethal", "ctmin"),
        z == tss_grid$z[i]
      )
  } else if (tss_grid$thresh[i] == "retreat") {
    data_subset <- microclimate_temps |>
      filter(
        thresh != "rest",
        z == tss_grid$z[i]
      )
  } else {
    data_subset <- microclimate_temps |>
      filter(
        z == tss_grid$z[i]
      )
  }

  tss_value <- data_subset |>
    mutate(
      pred = min_annual_tb > lethal & veg > tss_grid$veg[i]
    ) |>
    summarise(
      tp = sum(pred & presence),
      fp = sum(pred & !presence),
      fn = sum(!pred & presence),
      tn = sum(!pred & !presence)
    ) |>
    mutate(tss = (tp / (tp + fn)) + (tn / (tn + fp)) - 1) |>
    pull(tss)
  tss_grid$tss[i] <- tss_value

}

# save tss grid
saveRDS(tss_grid, "data/tss_grid.rds")
```

## Paper Figures

```{r plot-maps}
#| fig.align: "center"
#| fig.width: 8
#| fig.height: 8

microclimates_plot <- microclimate_temps |>
 filter(z %in% c(-0.03, 1.8)) |>
 ggplot() +
  geom_tile(
    aes(x = lon, y = lat, fill = min_annual_temp)
  ) +
  geom_tile(
    data = microclimate_temps |> filter(z %in% c(-0.03, 1.8), presence == 1),
    aes(x = lon, y = lat),
    fill = scales::alpha("green", 0.1)
  ) +
  geom_contour(
    aes(x = lon, y = lat, z = presence),
    color = "forestgreen",
    linewidth = 1
  ) +
  geom_contour(
    aes(x = lon, y = lat, z = min_annual_temp),
    color = "white",
    breaks = c(0, 5.35),
    linewidth = 0.5,
  ) +
  scale_y_continuous(
    expand = c(0, 0),
    breaks = seq(25, 37.5, by = 2.5),
    labels = paste0(seq(25, 37.5, by = 2.5), "°N")
  ) +
  scale_x_continuous(
    expand = c(0, 0),
    breaks = seq(-100, -75, by = 5),
    labels = paste0(seq(100, 75, by = -5), "°W"),
  ) +
  facet_wrap(
    vars(z),
    ncol = 1,
    labeller = labeller(
      z = as_labeller(
        c(
          "-0.03" = "Leaf Litter",
          "1.8" = "Canopy"
        )
      )
    )
  ) +
  scale_fill_viridis(
    option = "magma",
    name = "Minimum Annual Operative Temperature (°C)",
    breaks = seq(-10, 40, by = 5),
    guide = guide_colorbar(
      direction = "horizontal",
      title.position = "top",
      title.hjust = 0.5,
      barwidth = grid::unit(12, "cm"),
      barheight = grid::unit(0.35, "cm")
    )
  ) +
  coord_quickmap(
    xlim = c(-101, -75), ylim = c(24.5, 37.5)
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    axis.ticks = element_line(color = "black", linewidth = 0.25),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_text(size = 10),
    strip.text = element_text(size = 16, face = "bold", hjust = 0),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )

microclimates_plot
```


```{r plot-tss-results}
#| fig.align: "center"
#| fig.width: 6
#| fig.height: 8

tss_grid <- readRDS("data/tss_grid.rds")

# refactor threshold names for plotting
tss_grid$thresh <- factor(
  tss_grid$thresh,
  levels = c("lethal", "ctmin", "retreat", "rest")
)

tss_grid |>
  group_by(thresh) |>
  filter(tss == max(tss, na.rm = TRUE))

ggplot() +
  geom_tile(
    data = tss_grid,
    aes(x = veg, y = as.factor(z), fill = tss)
  ) +
  geom_point(
    data = tss_grid |>
      group_by(thresh) |>
      filter(tss == max(tss, na.rm = TRUE)) |>
      ungroup(),
    aes(x = veg, y = as.factor(z)),
    color = "red",
    size = 3,
    shape = 1
  ) +
  geom_hline(
    yintercept = 20.5, color = "white", linetype = "solid"
  ) +
  geom_hline(
    yintercept = 22, color = "white", linetype = "dashed"
  ) +
  scale_fill_viridis_b(
    name = "TSS",
    limits = c(
      min(tss_grid$tss, na.rm = TRUE), max(tss_grid$tss, na.rm = TRUE)
    ),
    breaks = seq(
      min(tss_grid$tss, na.rm = TRUE), max(tss_grid$tss, na.rm = TRUE),
      by = 0.05
    ),
    # only show labels for every other break
    labels = function(x) ifelse(seq_along(x) %% 2 == 1, x, ""),
    guide = guide_colorsteps(
      barheight = unit(8, "cm"),
      barwidth = unit(0.5, "cm")
    )
  ) +
  scale_x_continuous(
    breaks = seq(0, 1, by = 0.2),
    labels = scales::percent_format(accuracy = 1),
    expand = c(0, 0)
  ) +
  scale_y_discrete(
    breaks = unique(tss_grid$z),
    labels = function(x) {
      negative <- which(x < 0)
      x[negative[seq_along(negative) %% 2 == 1]] <- ""
      x
    },
    expand = c(0, 0),
  ) +
  facet_wrap(
    vars(thresh),
    ncol = 2,
    nrow = 2,
    axes = "all",
    labeller = labeller(
      thresh = as_labeller(
        c(
          lethal = "atop('Hard Physiological', 'Threshold (' * 0 * degree * 'C)')", # nolint
          ctmin = "atop('Soft Physiological', 'Threshold (' * CT[min] * ')')",
          retreat = "atop('Behavioral', 'Threshold (' * T[ret] * ')')",
          rest = "atop('Rest of', 'Range')"
        ),
        label_parsed
      )
    )
  ) +
  labs(
    x = "Vegetation Cover",
    y = "Distance from surface above or below leaf litter (m)"
  ) +
  theme_minimal() +
  theme(
    legend.position = "right",
    strip.text = element_text(size = 14),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
    axis.ticks = element_line(color = "black", linewidth = 0.25),
    axis.title = element_text(size = 16, lineheight = 1.25),
  )
```