---
title: "Time for Space Analysis of Retreating Temperatures"
format:
  html:
    code-fold: true
    fig-dpi: 300
---

```{r r-setup, warning = FALSE, message = FALSE}
# packages
library(tidyverse)
library(NicheMapR)
library(kableExtra)

# options
options(
  dplyr.summarise.inform = FALSE,
  knitr.table.html.attr = "quarto-disable-processing=true"
)

```

```{r read-and-process-survey-data}
# read in data
survey <- readRDS("data/sleepy-lizard-survey-data.rds")
ibutton <- readRDS("data/ibutton-data.rds")

# filter iButton data to match survey data
ibutton_survey <- ibutton |>
  filter(location == "ATL") |>
  mutate(year = year + 2000) |>
  filter(year >= min(survey$year) & year <= max(survey$year)) |>
  filter(paste(year, doy) %in% paste(survey$year, survey$doy)) |>
  left_join(
    survey |>
      select(year, doy, start_mod, end_mod) |>
      unique(),
    by = c("year", "doy")
  ) |>
  mutate(end_mod = ifelse(end_mod > 1440, 1440, end_mod)) |>
  filter(mod >= start_mod & mod <= end_mod) |>
  group_by(year, doy, microhabitat) |>
  summarise(
    mean_temp = mean(temp, na.rm = TRUE),
    .groups = "drop"
  ) |>
  pivot_wider(
    names_from = microhabitat,
    values_from = mean_temp
  ) |>
  rename(
    mean_temp_branch = branch,
    mean_temp_litter = leaflitter
  )

# combine survey and iButton data
survey_ibutton <- survey |> left_join(ibutton_survey, by = c("year", "doy"))
```

### Estimating Threshold Temperature for Presence

```{r plot-observation-probability, warning = FALSE, message = FALSE}
#| fig-align: "center"
#| fig-width: 4
#| fig-height: 4
#| out.width: 66%
survey_ibutton |>
  group_by(year, doy, mean_temp_branch, mean_temp_litter) |>
  summarise(
    count = n(),
    presence = ifelse(count > 1, 1, 0),
    .groups = "drop"
  ) |>
  ggplot(aes(x = mean_temp_branch, y = presence)) +
  geom_jitter(
    width = 0, height = 0.01, 
    color = "forestgreen", alpha = 0.5, size = 3
  ) +
  geom_smooth(
    method = "glm", method.args = list(family = "binomial"),
    color = "darkgreen",
    fill = "forestgreen",
    alpha = 0.2
  ) +
  theme_classic() +
  theme(
    panel.grid.major = element_line(color = "gray90")
  ) +
  labs(
    x = "Mean Branch Temp. (°C)",
    y = "Probability of Seeing at least ONE Lizard"
  )
```

```{r model-observation-probability}
survey_ibutton_model_data <- survey_ibutton |>
  group_by(year, doy, mean_temp_branch, mean_temp_litter) |>
  summarise(
    count = n(),
    presence = ifelse(count > 1, 1, 0),
    .groups = "drop"
  )

presence_model <- glm(
  presence ~ mean_temp_branch,
  data = survey_ibutton_model_data,
  family = "binomial"
)
summary(presence_model)

# predict temperature thresholds
tibble(probability = c(0.5, 0.1, 0.05, 0.01)) |>
  mutate(
    logit = log(probability / (1 - probability)),
    temp = round((logit - coef(presence_model)[1]) / coef(presence_model)[2], 2)
  ) |>
  select(probability, temp) |>
  rename(
    `Probability of Observation` = probability,
    `Air Temperature` = temp
  ) |>
  kable() |>
  kable_styling(
    full_width = FALSE,
    position = "center"
  )
```

### Estimating Threshold Temperature for Abundance

```{r plot-abundance-probability, warning = FALSE, message = FALSE}
#| fig-align: "center"
#| fig-width: 4
#| fig-height: 4
#| out.width: 66%
survey_ibutton |>
  group_by(year, doy, mean_temp_branch, mean_temp_litter) |>
  summarise(
    count = n(),
    presence = ifelse(count > 1, 1, 0),
    .groups = "drop"
  ) |>
  ggplot(aes(x = mean_temp_branch, y = count - 1)) +
  geom_jitter(
    width = 0, height = 0.01,
    color = "forestgreen", alpha = 0.5, size = 3
  ) +
  geom_smooth(
    method = "glm", method.args = list(family = "poisson"),
    color = "darkgreen",
    fill = "forestgreen",
    alpha = 0.2
  ) +
  theme_classic() +
  theme(
    panel.grid.major = element_line(color = "gray90")
  ) +
  labs(
    x = "Mean Branch Temp. (°C)",
    y = "Number of Lizards Observed"
  )
```

```{r model-abundance-probability}
abundance_model <- glm(
  count ~ mean_temp_branch,
  data = survey_ibutton_model_data,
  family = "poisson"
)
summary(abundance_model)

# predict temperature thresholds
tibble(counts = c(0.5, 1, 2, 5, 10)) |>
  mutate(
    log = log(counts),
    temp = round((log - coef(abundance_model)[1]) / coef(abundance_model)[2], 2)
  ) |>
  select(counts, temp) |>
  rename(
    `Expected Count` = counts,
    `Air Temperature` = temp
  ) |>
  kable() |>
  kable_styling(
    full_width = FALSE,
    position = "center"
  )





```